services:
  agriguard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    restart: unless-stopped
    container_name: agriguard-app

  mlflow:
    image: python:3.9-slim
    ports:
      - "5001:5000"
    volumes:
      - mlflow_data:/app/mlruns
      - mlflow_db:/app
    working_dir: /app
    command: >
      bash -c "pip install mlflow boto3 &&
               mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /app/mlruns"
    restart: unless-stopped
    container_name: mlflow-server

volumes:
  mlflow_data:
  mlflow_db:
