version: '3.8'

services:
  agriguard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    restart: unless-stopped
    container_name: agriguard-app

  mlflow:
    image: python:3.9-slim
    ports:
      - "5001:5000"  # Changed port to avoid conflict
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    working_dir: /app
    command: >
      bash -c "pip install mlflow boto3 &&
               mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /app/mlruns"
    restart: unless-stopped
    container_name: mlflow-server
    
  model-training:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    command: python src/mlops/mlflow_integration.py
    profiles:
      - training  # Only run when explicitly requested